[www]
user  = nobody
group = nobody

; Listen on all interfaces so nginx (different container) can reach us
listen = 0.0.0.0:9000

; Process manager
pm                   = dynamic
pm.max_children      = 10
pm.start_servers     = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests      = 500

; Send logs to Docker stdout/stderr
php_admin_value[error_log]     = /dev/stderr
php_admin_flag[log_errors]     = on
catch_workers_output           = yes